export const NO_RULESET_MATCHED = "No ruleset is matches the structure of the requested document"
export const SCRAPE_ERROR = "Scraping source failed"
export const NO_RESULTS = "No results were found for the query"
export const NO_BODY_FOUND = "Could not find body of document"
export const INCORRECT_CREDENTIALS = "Credentials were incorrect"
export const NOT_PERMITTED = "You are not authorized to do this"
