version: '2'
services:
  mongo:
    image: mongo:4.4
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin 
      MONGO_INITDB_ROOT_PASSWORD: admin 

  
  nginx:
    build:
      context: nginx
      dockerfile: Dockerfile
    network_mode: "host"
