FROM node:16-alpine as build
WORKDIR /usr/src/
COPY yarn.lock package.json tsconfig.json ./
COPY packages/fe /usr/src/packages/fe
COPY packages/shared /usr/src/packages/shared
WORKDIR /usr/src/packages/fe
RUN yarn install --no-cache
RUN yarn build 

FROM nginx:alpine                                                                                               
RUN rm /etc/nginx/conf.d/default.conf
COPY docker/prod/nginx /etc/nginx
COPY --from=build /usr/src/packages/fe/dist /usr/share/nginx/html                                                                        
