FROM node:16-alpine
WORKDIR /usr/src/
COPY yarn.lock package.json tsconfig.json ./
COPY packages/shared/package.json /usr/src/packages/shared/package.json
WORKDIR /usr/src/packages/shared
RUN yarn install --no-cache
COPY packages/api/package.json /usr/src/packages/api/package.json
WORKDIR /usr/src/packages/api
RUN yarn install --no-cache
COPY packages/api /usr/src/packages/api
COPY packages/events /usr/src/packages/events
COPY packages/shared /usr/src/packages/shared
RUN yarn build 
CMD ["yarn", "start"]
