FROM node:16-alpine
WORKDIR /usr/src/
COPY yarn.lock package.json tsconfig.json ./
COPY packages/shared/package.json /usr/src/packages/shared/package.json
WORKDIR /usr/src/packages/shared
RUN yarn install --no-cache
COPY packages/migrations/package.json /usr/src/packages/migrations/package.json
WORKDIR /usr/src/packages/migrations
RUN yarn install --no-cache
COPY packages/shared /usr/src/packages/shared
COPY packages/migrations /usr/src/packages/migrations
