FROM node:16-alpine
WORKDIR /usr/src/
COPY yarn.lock package.json tsconfig.json ./
COPY packages/api /usr/src/packages/api
COPY packages/events /usr/src/packages/events
COPY packages/shared /usr/src/packages/shared
WORKDIR /usr/src/packages/api
RUN yarn install --no-cache
RUN yarn build 
CMD ["yarn", "start"]
