FROM node:16-alpine
WORKDIR /usr/src/
COPY yarn.lock package.json tsconfig.json ./
COPY packages/shared/package.json /usr/src/packages/shared/package.json
COPY packages/db/package.json /usr/src/packages/db/package.json
COPY packages/migrations/package.json /usr/src/packages/migrations/package.json
WORKDIR /usr/src/packages/migrations
COPY packages/shared /usr/src/packages/shared
COPY packages/migrations /usr/src/packages/migrations
COPY packages/db /usr/src/packages/db
RUN yarn install --no-cache --production
