FROM node:16-alpine
WORKDIR /usr/src/
COPY yarn.lock package.json tsconfig.json ./

COPY packages/shared/package.json /usr/src/packages/shared/package.json
COPY packages/fe/package.json /usr/src/packages/fe/package.json

WORKDIR /usr/src/packages/fe
RUN yarn install --no-cache
COPY packages/shared /usr/src/packages/shared
COPY packages/fe /usr/src/packages/fe
RUN yarn build 

CMD ["yarn", "start"]
