apiVersion: v1
kind: Service
metadata:
  name: fe-service
  labels:
    app: fe
spec:
  ports:
    - port: 3000
  selector:
    app: fe
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fe-deployment
  labels:
    app: fe
spec:
  selector:
    matchLabels:
      app: fe
  template:
    metadata:
      labels:
        app: fe
    spec:
      containers:
        - name: fe
          image: {{ .Values.werf.image.fe }} 
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: api-service
  labels:
    app: api 
spec:
  ports:
    - port: 5000 
  selector:
    app: api 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  labels:
    app: api 
spec:
  selector:
    matchLabels:
      app: api 
  template:
    metadata:
      labels:
        app: api 
    spec:
      containers:
        - name: api 
          image: {{ .Values.werf.image.api }} 
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-service
  labels:
    app: mongo 
spec:
  ports:
    - port: 27017 
  selector:
    app: mongo 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-deployment
  labels:
    app: mongo 
spec:
  selector:
    matchLabels:
      app: mongo 
  template:
    metadata:
      labels:
        app: mongo 
    spec:
      containers:
        - name: mongo 
          image: bitnami/mongodb:4.4 
          ports:
            - containerPort: 27017
