apiVersion: v1
kind: Service
metadata:
  name: fe-service
  labels:
    app: fe
spec:
  ports:
    - port: 3000
  selector:
    app: fe
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fe-deployment
  labels:
    app: fe
spec:
  selector:
    matchLabels:
      app: fe
  template:
    metadata:
      labels:
        app: fe
    spec:
      containers:
        - name: fe
          image: {{ .Values.werf.image.fe }} 
          ports:
            - containerPort: 3000
