name: learn-github-actions
on: [push]
jobs:
  converge:
    name: Converge
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      #- name: Login to Docker Hub
        #uses: docker/login-action@v1
        #with:
          #username: ${{ secrets.DOCKERHUB_USERNAME }}
          #password: ${{ secrets.DOCKERHUB_PW }}

      - name: Converge
        uses: werf/actions/converge@v1.2
        with:
          env: prod 
          kube-config-base64-data: ${{ secrets.KUBE_CONFIG_BASE64_DATA }}
        env:
          WERF_SET_VITE_URL: "VITE_URL=xanto.lawbrador.nl"
